remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: "Haohua Liu"
minimal_mistakes_skin: "air"
plugins:
  - "jekyll-include-cache"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
   # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true